name: "homelab updater"
description: "small go tool to upate my homelab repo's dependencies"
author: "loeken"
inputs:
  chart_name:
    description: 'the name of the chart'
    required: true
    default: 'authelia'
  values_chart_name:
    description: 'the name of the chart'
    required: true
    default: 'certmanager'
  remote_chart_name:
    description: 'the name of the chart in loeken/helm-charts'
    required: true
    default: 'false'
  chart_type:
    description: 'if this is optional/core chart'
    required: true
  github_user:
    description: 'which github user owns the repo'
    required: true
    default: 'authelia'
  github_repo:
    description: 'the name of the github repo'
    required: true
    default: authelia
  docker_image:
    description: address of the image
    required: true
    default: authelia/authelia
  chart_version:
    default: "authelia-0.8.55"
    required: true
    description: "the version of the helm chart"
  chart_index_url:
    default: "https://charts.authelia.com/index.yaml"
    required: true
    description: "the url of the charts index"
  dockertag:
    default: main
    required: true
    description: the docker tag
  release_remove_string:
    description: 'a string to be removed from the version'
    required: true
    default: 'authelia'
  type:
    description: jq syntax to extract last release
    required: true
    default: '.tag_name'
  github_token:
    description: the github token
    required: true
  self_managed_image:
    description: if image is managed by me
    required: true
    default: "false"
  self_managed_chart:
    description: if helm chart is managed by me
    required: true
    default: "false"
  myOutput:
    description: "Output from the action"
outputs:
  latest_release:
    description: "released version of app"
runs:
  using: "docker"
  image: "Dockerfile"
