authelia:
  chartVersion: 0.9.9
  enabled: false
  filesystem:
    enabled: true
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  smtp:
    enabled: false
    host: mail.example.com
    port: 587
    sender: authelia@example.com
    username: authelia@example.com
  storageClass: local-path
certmanager:
  chartVersion: 1.16.2
  enabled: false
cloudflaretunnel:
  enabled: false
clusterIssuer: letsencrypt-staging
democratic_iscsi:
  chartVersion: 0.14.2
  enabled: false
democratic_nfs:
  chartVersion: 0.14.2
  enabled: false
domain: example.com
externaldns:
  chartVersion: 8.6.0
  enabled: false
githubRepo: homelab-example
githubUser: loeken
homeassistant:
  chartVersion: 2024.11.1
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  storageClass: local-path
  useAuthelia: false
jellyfin:
  cache:
    enabled: true
    size: 10Gi
    storageClass: local-path
  chartVersion: 10.10.1
  config:
    enabled: true
    size: 1Gi
    storageClass: local-path
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: false
    nginx:
      enabled: false
  useAuthelia: false
jellyseerr:
  chartVersion: 2.1.0
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  storageClass: local-path
  useAuthelia: false
k10:
  chartVersion: 7.0.14
  enabled: false
  storageClass: local-path
linkerd:
  enabled: false
loki:
  alertmanager:
    enabled: false
    ingress:
      cloudflaretunnel:
        enabled: true
    storageClass: local-path
    storageSize: 10Gi
  chartVersion: 2.10.2
  enabled: false
  filebeat:
    enabled: false
  fluentbit:
    enabled: false
  grafana:
    storageClass: local-path
    storageSize: 10Gi
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  logstash:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: true
    storageClass: local-path
    storageSize: 10Gi
  promtail:
    enabled: true
  storageClass: local-path
  storageSize: 10Gi
nextcloud:
  chartVersion: 6.2.3
  data:
    size: 10Gi
    storageClass: local-path
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  smtp:
    domain: example.com
    host: mail.example.com
    port: 587
    sender: nextcloud@example.com
    username: nextcloud@example.com
  storageClass: local-path
  useAuthelia: false
nfsprovisioner:
  chartVersion: 4.0.18
  enabled: true
  ip: 172.16.137.200
nginxingress:
  chartVersion: 11.5.4
  enabled: false
nzbget:
  chartVersion: 1.3.2
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 10Gi
  storageClass: local-path
  useAuthelia: false
prowlarr:
  chartVersion: 1.25.4
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 1Gi
  storageClass: local-path
  useAuthelia: false
radarr:
  chartVersion: 5.14.0
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 1Gi
  storageClass: local-path
  useAuthelia: false
robusta:
  enabled: false
rtorrentflood:
  chartVersion: 4.8.2
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 10Gi
  storageClass: local-path
  useAuthelia: false
sharedmedia:
  enabled: false
  size: 100Gi
  storageClass: nfs-client
sonarr:
  chartVersion: 4.0.10
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 1Gi
  storageClass: local-path
  useAuthelia: false
storageClass: local-path
vaultwarden:
  chartVersion: 1.32.0
  enabled: false
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
  size: 10Gi
  storageClass: local-path
  useAuthelia: true
volumesnapshots:
  enabled: true
whoami:
  chartVersion: 5.2.0
  enabled: true
  ingress:
    cloudflaretunnel:
      enabled: true
    nginx:
      enabled: false
