name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        repo:
          - chartName: authelia
            github_user: authelia
            github_repo: chartrepo
            images:
              - authelia/authelia
            release: v4.37.5
            dockertag: master
            release_remove_string: authelia-

          - chartName: cert-manager
            github_user: cert-manager
            github_repo: cert-manager
            images:
              - quay.io/jetstack/cert-manager-cainjector
              - quay.io/jetstack/cert-manager-controller
              - quay.io/jetstack/cert-manager-webhook
            release: v1.11.0
            dockertag: v1.11.0
            release_remove_string: ""

          - chartName: nginxingress
            github_user: nginxinc
            github_repo: kubernetes-ingress
            images:
              - nginx/nginx-ingress
            release: v3.0.2
            dockertag: edge-alpine
            release_remove_string: ""

          - chartName: sealedSecrets
            github_user: bitnami-labs
            github_repo: sealed-secrets
            images:
              - bitnami/sealed-secrets-controller
            release: v0.19.5
            dockertag: v0.19.5
            release_remove_string: sealed-secrets-
    steps:

      - uses: actions/checkout@main

      - name: Install yq
        id: get_chart_version
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          cd $GITHUB_WORKSPACE
          echo "CHART_VERSION=$(cat values.yaml | yq -r '.${{ matrix.repo.chartName }}.chartVersion')" >> $GITHUB_ENV


      - name: debug
        run: |
          echo ${{ env.CHART_VERSION }}
      - name: test for pending updates

        # Put your action repo here
        uses: loeken/homelab-updater@main
        with:
          github_user: ${{ matrix.repo.github_user }}
          github_repo: ${{ matrix.repo.github_repo }}
          github_token: ${{ secrets.UPDATE_TOKEN }}
          release: ${{ env.CHART_VERSION }}
          chart_name: ${{ matrix.repo.chartName }}
          release_remove_string: ${{ matrix.repo.release_remove_string }}

      - name: Run Trivy vulnerability scanner
        run: |
          for image in ${{ join(matrix.repo.images, ' ') }}; do
            echo "Running trivy for $image"
            docker run --rm aquasec/trivy image $image:${{ matrix.repo.dockertag }}
          done