name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        repo:
          - chartName: authelia
            valuesChartName: authelia
            chartType: optional
            github_user: authelia
            github_repo: authelia
            images:
              - authelia/authelia
            release_remove_string: authelia-
            chart_index_url: https://charts.authelia.com/index.yaml
            dockertagprefix: ""

          - chartName: cert-manager
            valuesChartName: certmanager
            chartType: optional
            github_user: cert-manager
            github_repo: cert-manager
            images:
              - quay.io/jetstack/cert-manager-cainjector
              - quay.io/jetstack/cert-manager-controller
              - quay.io/jetstack/cert-manager-webhook
            release_remove_string: ""
            chart_index_url: https://charts.jetstack.io/index.yaml
            dockertagprefix: "v"

          - chartName: sealed-secrets
            valuesChartName: sealedsecrets
            chartType: core
            github_user: bitnami-labs
            github_repo: sealed-secrets
            images:
              - bitnami/sealed-secrets-controller
            release_remove_string: sealed-secrets-
            chart_index_url: https://bitnami-labs.github.io/sealed-secrets/index.yaml
            dockertagprefix: "v"

          - chartName: democratic-csi
            valuesChartName: democratic_iscsi
            chartType: optional
            github_user: democratic-csi
            github_repo: democratic-csi
            images:
              - democraticcsi/democratic-csi
            release_remove_string: democratic-csi-
            chart_index_url: https://democratic-csi.github.io/charts/index.yaml
            dockertagprefix: "v"

          - chartName: democratic-csi
            valuesChartName: democratic_nfs
            chartType: optional
            github_user: democratic-csi
            github_repo: democratic-csi
            images:
              - democraticcsi/democratic-csi
            release_remove_string: democratic-csi-
            chart_index_url: https://democratic-csi.github.io/charts/index.yaml
            dockertagprefix: "v"

          - chartName: home-assistant
            chartType: optional
            valuesChartName: ha
            github_user: home-assistant
            github_repo: core
            images:
              -  loeken/home-assistant
            self_managed_image: 'true'
            self_managed_chart: 'true'
            remote_chart_name: home-assistant
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagprefix: ""

          - chartName: external-dns
            chartType: optional
            valuesChartName: externaldns
            github_user: kubernetes-sigs
            github_repo: external-dns
            images:
              -  bitnami/external-dns
            chart_index_url: https://charts.bitnami.com/bitnami/index.yaml
            dockertagprefix: ""

          - chartName: jellyfin
            chartType: optional
            valuesChartName: jellyfin
            github_user: jellyfin
            github_repo: jellyfin
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/jellyfin
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagprefix: ""

          - chartName: jellyseerr
            chartType: optional
            valuesChartName: jellyseerr
            github_user: Fallenbagel
            github_repo: jellyseerr
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/jellyseerr
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagprefix: ""

          - chartName: k10
            chartType: optional
            valuesChartName: k10
            github_user: kasten-io
            github_repo: k10
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              - gcr.io/kasten-images/init
              - gcr.io/kasten-images/grafana
              - gcr.io/kasten-images/configmap-reload
              - gcr.io/kasten-images/prometheus
              - gcr.io/kasten-images/auth
              - gcr.io/kasten-images/upgrade
              - gcr.io/kasten-images/catalog
              # - ghcr.io/kanisterio/kanister-tools
              - gcr.io/kasten-images/controllermanager
              - gcr.io/kasten-images/crypto
              - gcr.io/kasten-images/events
              - gcr.io/kasten-images/garbagecollector
              - gcr.io/kasten-images/bloblifecyclemanager
              - gcr.io/kasten-images/vbrintegrationapi
              - gcr.io/kasten-images/executor
              - gcr.io/kasten-images/cephtool
              - gcr.io/kasten-images/jobs
              - gcr.io/kasten-images/logging
              - gcr.io/kasten-images/metering
              - gcr.io/kasten-images/state
              - gcr.io/kasten-images/admin
              - gcr.io/kasten-images/aggregatedapis
              - gcr.io/kasten-images/frontend
              - gcr.io/kasten-images/kanister
              - gcr.io/kasten-images/emissary
            chart_index_url: https://charts.kasten.io/index.yaml
            dockertagprefix: ""

          - chartName: loki-stack
            chartType: optional
            valuesChartName: loki
            github_user: grafana
            github_repo: loki
            images:
              -  grafana/loki
            chart_index_url: https://grafana.github.io/helm-charts/index.yaml
            dockertagprefix: ""

          - chartName: nextcloud
            chartType: optional
            valuesChartName: nextcloud
            github_user: nextcloud
            github_repo: nextcloud
            images:
              - nextcloud
            chart_index_url: https://nextcloud.github.io/helm/index.yaml
            dockertagprefix: ""
            dockertagoverride: 26.0.1-fpm-alpine

          - chartName: nfs-subdir-external-provisioner
            chartType: optional
            valuesChartName: nfsprovisioner
            github_user: kubernetes-sigs
            github_repo: nfs-subdir-external-provisioner
            images:
              -  registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
            chart_index_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/index.yaml
            dockertagprefix: ""
            release_remove_string: "nfs-subdir-external-provisioner-"
            dockertagoverride: v4.0.2

          - chartName: nginx-ingress
            valuesChartName: nginxingress
            chartType: optional
            github_user: nginxinc
            github_repo: kubernetes-ingress
            images:
              - nginx/nginx-ingress
            release_remove_string: ""
            chart_index_url: https://helm.nginx.com/stable/index.yaml

          - chartName: nzbget
            chartType: optional
            valuesChartName: nzbget
            github_user: nzbget
            github_repo: nzbget
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/nzbget
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
  
          - chartName: prowlarr
            chartType: optional
            valuesChartName: prowlarr
            github_user: Prowlarr
            github_repo: Prowlarr
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/prowlarr
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagoverride: develop-version-1.3.2.3006

          - chartName: radarr
            chartType: optional
            valuesChartName: radarr
            github_user: Radarr
            github_repo: Radarr
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/radarr
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagprefix: version-
          
          - chartName: rtorrent-flood
            chartType: optional
            valuesChartName: rtorrentflood
            github_user: jesec
            github_repo: flood
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/rtorrent-flood
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml

          - chartName: sonarr
            chartType: optional
            valuesChartName: sonarr
            github_user: Sonarr
            github_repo: Sonarr
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/sonarr
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagoverride: release-3.0.9.1549

          - chartName: vaultwarden
            chartType: optional
            valuesChartName: vaultwarden
            github_user: dani-garcia
            github_repo: vaultwarden
            self_managed_image: 'true'
            self_managed_chart: 'true'
            images:
              -  loeken/vaultwarden
            chart_index_url: https://loeken.github.io/helm-charts/index.yaml
            dockertagoverride: 1.28.1-alpine

          - chartName: whoami
            chartType: optional
            valuesChartName: whoami
            github_user: traefik
            github_repo: whoami
            images:
              -  traefik/whoami
            chart_index_url: https://gitlab.com/api/v4/projects/37200623/packages/helm/stable/index.yaml
            dockertagprefix: "v"
    steps:

      - uses: actions/checkout@main

      - name: Install yq
        id: get_chart_version
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          cd $GITHUB_WORKSPACE

          echo "CHART_VERSION=$(cat values-${{ matrix.repo.chartType }}.yaml | yq -r '.${{ matrix.repo.valuesChartName }}.chartVersion')"
          echo "CHART_VERSION=$(cat values-${{ matrix.repo.chartType }}.yaml | yq -r '.${{ matrix.repo.valuesChartName }}.chartVersion')" >> $GITHUB_ENV

      - name: debug
        run: |
          echo ${{ env.CHART_VERSION }}
      - name: test for pending updates
        # Put your action repo here
        id: test_updates
        uses: ./
        #uses: loeken/homelab-updater@main
        with:
          github_user: ${{ matrix.repo.github_user }}
          github_repo: ${{ matrix.repo.github_repo }}
          github_token: ${{ secrets.UPDATE_TOKEN }}
          chart_index_url: ${{ matrix.repo.chart_index_url }}
          chart_name: ${{ matrix.repo.chartName }}
          values_chart_name: ${{ matrix.repo.valuesChartName }}
          chart_version: ${{ env.CHART_VERSION }}
          release_remove_string: ${{ matrix.repo.release_remove_string }}
          chart_type: ${{ matrix.repo.chartType }}
          self_managed_image: ${{ matrix.repo.self_managed_image }}
          docker_image: ${{ matrix.repo.docker_image }}
          remote_chart_name: ${{ matrix.repo.remote_chart_name }}
          self_managed_chart: ${{ matrix.repo.self_managed_chart }}
        env:
          GITHUB_ENV: ${{ github.workspace }}/.env

      - name: Read output file
        id: read_output
        run: |
          echo "::set-output name=latest_app_release::$(cat output.txt | grep LATEST_APP_RELEASE= | cut -d'=' -f2)"
          echo "::set-output name=latest_chart_release::$(cat output.txt | grep LATEST_CHART_RELEASE= | cut -d'=' -f2)"


      - name: Save release output
        run: |
          echo "LATEST_APP_RELEASE=${{ steps.read_output.outputs.latest_app_release }}" >> $GITHUB_ENV
          echo "LATEST_CHART_RELEASE=${{ steps.read_output.outputs.latest_chart_release }}" >> $GITHUB_ENV


      - name: Display release value
        run: |
          echo "Latest APP Release value: $LATEST_APP_RELEASE"
          echo "Latest CHART Release value: $LATEST_CHART_RELEASE"
        
      - name: Run Trivy vulnerability scanner
        run: |
          for image in ${{ join(matrix.repo.images, ' ') }}; do
            echo "Running trivy for $image"
            if [ "${{ matrix.repo.dockertagoverride }}" != "" ]; then
              docker run --rm aquasec/trivy image $image:${{ matrix.repo.dockertagoverride }}
            else
              docker run --rm aquasec/trivy image $image:${{ matrix.repo.dockertagprefix }}$LATEST_APP_RELEASE
            fi
          done
